[app]
name = "keyauth"
key  = "this is your app key"

[http]
host = "127.0.0.1"
port = "8848"

[grpc]
host = "127.0.0.1"
port = "18848"


[keyauth]
host = "127.0.0.1"
port = "18050"
client_id = "sdd"
client_secret = "sdd"




[mongodb]
endpoints = ["192.168.83.149:27017"]
username = "keyauth"
password = "123"
database = "keyauth"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"