[app]
name = "keyauth"
key  = "this is your app key"

[app.http]
host = "127.0.0.1"
port = "8848"

[app.grpc]
host = "127.0.0.1"
port = "18848"

[mongodb]
endpoints = ["192.168.83.149:27017"]
username = "keyauth"
password = "123"
database = "keyauth"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"